[tool_alias]
lefthook = "github:evilmartians/lefthook"

[tools]
node = "26"
bun = "1.3.14"
[tools."github:evilmartians/lefthook"]
version = "latest"
postinstall = "lefthook install"
[tools."github:evilmartians/lefthook".platforms.linux-x64]
asset_pattern = "lefthook_*_Linux_x86_64.gz"
bin = "lefthook"
[tools."github:evilmartians/lefthook".platforms.macos-arm64]
asset_pattern = "lefthook_*_MacOS_arm64.gz"
bin = "lefthook"
[tools."github:evilmartians/lefthook".platforms.windows_x86_64]
asset_pattern = "lefthook_*_Windows_x86_64.gz"
bin = "lefthook.exe"
