[tool_alias]
lefthook = "github:evilmartians/lefthook"

[tools]
node = "26"
bun = "1.3.14"
[tools.lefthook]
version = "latest"
postinstall = "lefthook install"
[tools.lefthook.platforms.linux-x64]
asset_pattern = "lefthook_*_Linux_x86_64.gz"
bin = "lefthook"
[tools.lefthook.platforms.windows_x86_64]
asset_pattern = "lefthook_*_Windows_x86_64.gz"
bin = "lefthook.exe"
