[build]
base = "/"
publish = "dist"
command = "yarn generate --fail-on-error"

[context.production]
  [context.production.environment]
    STRAPI_URL = "https://strapi.gagnecliche.dev"

[context.deploy-preview]
  [context.deploy-preview.environment]
    STRAPI_URL = "https://strapi.gagnecliche.dev"