[build]
base = "/"
publish = "dist"
command = "yarn generate --fail-on-error"


[context.production]
  [context.production.environment]
    EMAILJS_SERVICEID = "portfolio_mn83wvd"
    EMAILJS_TEMPLATEID = "default_58v68tt"
    EMAILJS_USERID = "fQsPv5E3xcb_a9l0T"
    GRECAPTCHA_SITEKEY = "6Lf9bhwiAAAAAK_W_RUMWNTijtLkuTaUNXUmrYd2"

[context.deploy-preview]
  [context.deploy-preview.environment]
    EMAILJS_SERVICEID = "portfolio_mn83wvd"
    EMAILJS_TEMPLATEID = "dev-test_ge2auoi"
    EMAILJS_USERID = "fQsPv5E3xcb_a9l0T"
    GRECAPTCHA_SITEKEY = "6Lf9bhwiAAAAAK_W_RUMWNTijtLkuTaUNXUmrYd2"