/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123SessionChar125RouteImport } from './routes/{-$session}'

const Char123SessionChar125Route = Char123SessionChar125RouteImport.update({
  id: '/{-$session}',
  path: '/{-$session}',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/{-$session}': typeof Char123SessionChar125Route
}
export interface FileRoutesByTo {
  '/{-$session}': typeof Char123SessionChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$session}': typeof Char123SessionChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/{-$session}'
  fileRoutesByTo: FileRoutesByTo
  to: '/{-$session}'
  id: '__root__' | '/{-$session}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123SessionChar125Route: typeof Char123SessionChar125Route
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/{-$session}': {
      id: '/{-$session}'
      path: '/{-$session}'
      fullPath: '/{-$session}'
      preLoaderRoute: typeof Char123SessionChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Char123SessionChar125Route: Char123SessionChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
